version: "3.9"
services:
  front:
    build: .
    volumes:
      - ./front:/front
      - node_modules:/front/node_modules
    working_dir: /front
    tty: true
    ports:
      - 3000:3000
      - "5555:5555"
    command: npm run dev
  db:
    image: postgres:16.0
    volumes: 
      - db:/var/lib/postgresql/data
    env_file:
      - ./front/.env
    ports:
      - 5432:5432
volumes:
  node_modules:
  db: